version: '0.0.1'

services:
  postgresqldb:
    image: postgres:alpine
    container_name: 'java-postgres'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=test_docker_db'
    volumes:
      - './postgres-data:/var/lib/postgresql/data'

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - '8080:8080'
    environment:
      - 'POSTGRES_HOST=postgresqldb:5432'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=test_docker_db'
    depends_on:
      - postgresqldb
